### ISSUE TITLE
Debug issues with pandas 1.3.0

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1070]
Several test / build failures appear when using pandas v1.3.0, e.g. #1056 (having to do with the way errors are reported in data package validation) and #1057 (some kind of pyarrow import error while running the docs build).  Pinning to v1.2.x avoids the issues, but we should figure out why stuff is suddenly breaking.

We should also really set up our requirements in a form that the dependabot can read, so that we catch these issues as soon as they arise.

**Comment by zaneselvans** [comment]
## Parsing datapackage validation errors
The proximate problem here (reported in #1057) has to do with changes in the way data package validation errors are reported. This was easy to hack around by parsing the JSON slightly differently.

## Assigning standard data types to the BGA table
But the error reports were being triggered by a real error -- it turns out that we weren't imposing standardized data types on the BGA table, which is created in the harvesting process, after data types have been imposed on the data tables.  After entity harvesting & resolution we impose types on the entity tables, but we weren't standardizing the BGA table, and something about how pandas manages data types apparently changed between 1.2.5 and 1.3.2, with the consequence being that the `plant_id_eia` values in the BGA table were showing up as floats.  This was easy to fix by applying standard data types to the BGA table at the end of its transform / creation function.  However, there appear to be (at least) two additional problems now.

## Import error during docs build
There's some kind of version parsing issue coming up when Sphinx attempts to generate the documentation. Not sure what's going on there. It seems to involve some compatibility check between pandas and pyarrow. Here's the stack trace:

```
Warning, treated as error:
autodoc: failed to import module 'pudl'; the following exception was raised:
Traceback (most recent call last):
  File "/home/zane/code/catalyst/pudl/.env_pudl/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "/home/zane/miniconda3/envs/pudl-dev/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/zane/code/catalyst/pudl/.env_pudl/lib/python3.9/site-packages/pudl/__init__.py", line 8, in <module>
    import pudl.analysis.allocate_net_gen
  File "/home/zane/code/catalyst/pudl/.env_pudl/lib/python3.9/site-packages/pudl/analysis/allocate_net_gen.py", line 95, in <module>
    import pandas as pd
  File "/home/zane/code/catalyst/pudl/.env_pudl/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/zane/code/catalyst/pudl/.env_pudl/lib/python3.9/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/zane/code/catalyst/pudl/.env_pudl/lib/python3.9/site-packages/pandas/compat/pyarrow.py", line 9, in <module>
    _palv = Version(_pa_version)
  File "/home/zane/code/catalyst/pudl/.env_pudl/lib/python3.9/site-packages/pandas/util/version/__init__.py", line 339, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

## NERC Region inconsistency
Then I tried to run a full ETL on all the years, and got a consistency error in the entity harvesting / resolution process, using exactly the same data and settings as we used for the v0.4.0 release, so I'm guessing this is also somehow linked to changes in pandas and potentially how it manages data types... The failed assertion:
```
AssertionError: Harvesting of nerc_region is too inconsistent at 0.601.
```
I wonder how many additional issues will come up...

**Comment by zaneselvans** [comment]
The issue with the Sphinx doc build appears to be due to the fact that the `pyarrow` module is mocked for building on ReadTheDocs, but pandas is doing a check to see if the version of pyarrow installed is compatible, and to do that it needs to be able to look up the version of the package, which it can't do because it's mocked. Commenting `pyarrow` out of the list of mocked packages makes the error go away locally, but then the docs build till fail on RTD because the `snappy` library isn't installed there.

**Comment by zaneselvans** [comment]
RTD now lets you specify apt packages to install within the Docker container that's doing the build of the docs, so I updated our `.readthedocs.yaml` file to install `libsnappy-dev` and now we don't need to mock any packages, so this all works.

**Comment by zaneselvans** [comment]
It seems like the problem with the NERC regions being inconsistent had to do with the fact that it's a categorical value, and when you `df.groupby()` on a categorical, you have to set `observed=True` otherwise every possible value of the categorical shows up in every group, generally with a bunch of Null values. Changing these `groupby()` calls in `pudl.transform.eia._occurence_consistencty()` seems to have fixed the problem:

```py
    occur = (
        col_df
        .groupby(by=cols_to_consit, observed=True)
        .agg({'table': "count"})
        .reset_index()
        .rename(columns={'table': 'entity_occurences'})
    )
```
And a bit later:
```py
ge(occur, on=cols_to_consit)

    # determine how many instances of each of the records in col exist
    consist_df = (
        col_df
        .groupby(by=cols_to_consit + [col], observed=True)
        .agg({'table': 'count'})
        .reset_index()
        .rename(columns={'table': 'record_occurences'})
    )
```

However, it's mysterious why this would have been working previously...

**Comment by zaneselvans** [comment]
Once we get beyond the harvesting process, something goes wrong in the assignment of boiler-generator-associations. In `pudl.transform.eia._boiler_generator_assn() we're getting an assertion error: 
```
AssertionError: Inconsistent inter-annual BGA assignment!
```

Looking at the warnings that are getting printed out above that, I see that in the midst of the BGA process, the `plant_id_eia` values are being treated as `float` values, which is wrong.  Something is up in there.
```
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=1004.0, unit_id_pudl=3, unit_id_eia=['1' 'G108' 'CT1']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=1904.0, unit_id_pudl=3, unit_id_eia=['HBR0' 'BDS0']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=1927.0, unit_id_pudl=2, unit_id_eia=['RIV0' 'HBR0']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=4040.0, unit_id_pudl=1, unit_id_eia=['PWG1' 'PWG2']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=7242.0, unit_id_pudl=1, unit_id_eia=['CC1' 'CC2']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=7757.0, unit_id_pudl=1, unit_id_eia=['CC1' 'CC2']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=10725.0, unit_id_pudl=1, unit_id_eia=['F801' 'F802']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=50973.0, unit_id_pudl=1, unit_id_eia=['BLK1' 'BLK2' 'BLK3']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=55153.0, unit_id_pudl=1, unit_id_eia=['STG1' 'STG2']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=55309.0, unit_id_pudl=1, unit_id_eia=['SMR1' 'SMR2']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=55502.0, unit_id_pudl=1, unit_id_eia=['CC1' 'G801' 'CC2']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=55701.0, unit_id_pudl=1, unit_id_eia=['CC1' 'G961']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=56041.0, unit_id_pudl=1, unit_id_eia=['NGS' 'MGS']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=56309.0, unit_id_pudl=1, unit_id_eia=['G401' 'G402']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=56350.0, unit_id_pudl=1, unit_id_eia=['BLK1' '115']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=56350.0, unit_id_pudl=2, unit_id_eia=['BLK2' '116']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=56998.0, unit_id_pudl=1, unit_id_eia=['43' 'PB4']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=56998.0, unit_id_pudl=2, unit_id_eia=['53' 'PB5']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=57666.0, unit_id_pudl=1, unit_id_eia=['1' '2']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=57794.0, unit_id_pudl=1, unit_id_eia=['CC01' 'CC02']
2021-08-23 15:43:40 [ WARNING] pudl.transform.eia:784 Multiple EIA unit codes:plant_id_eia=60786.0, unit_id_pudl=1, unit_id_eia=['4343' '4141']
```

There are a bunch of calls to `astype()` in `pudl.transform.eia._boiler_generator_assn()` so it seemed likely that this is a data type issue somehow. Cleaning those up to use the canonical types of the columns didn't fix the problem.

I note that a bunch of the `unit_id_pudl` values are getting set to zero, for the ones where there's no real Unit ID.  That seems weird, given that in the current database, and in the current `bga_eia860()` there are no `unit_id_pudl` values that are zero. Shouldn't they be NA instead? I guess they're all getting dropped in the filter that happens at the end of the BGA function:
```py
if not debug:
    bga_out = (
        bga_out[
            ~bga_out.missing_from_923
            & ~bga_out.plant_w_bad_generator
            & ~bga_out.unmapped_but_in_923
            & ~bga_out.unmapped
        ]
)
```
