### ISSUE TITLE
No module named 'setuptools'

### ISSUE THREAD

**Issue by Wheelspawn** [catalyst-cooperative/pudl#1383]
### Describe the bug
Cannot complete [development setup](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/dev_setup.html) because my setup fails when I run `conda env create --name pudl-dev --file devtools/environment.yml` on the command line.

### Bug Severity
Cannot progress through the rest of the documentation.

### To Reproduce
Follow the instructions in the Development Setup documentation. Install miniconda into the virtual machine and then create the conda environment.

### Expected behavior
Expected environment to set up without errors and then be able to [create a workspace](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/dev_setup.html#creating-a-workspace). As it currently stands, the `pudl_setup` command cannot be found, which I suspect is due to the failure in setting up my development environment.

### Additional context
Using Fedora Workstation 35 in VMWare Workstation 16.

The full bug report:
```
Pip subprocess error:
ERROR: Exception:
Traceback (most recent call last):
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 338, in run
    requirement_set = resolver.resolve(
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 482, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 374, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 214, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 205, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 201, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 281, in __init__
    super().__init__(
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 292, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 546, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 47, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 106, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 83, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 332, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/pip-build-env-ajd08x5_/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 15, in <module>
    from .builders.wheel import WheelBuilder
  File "/tmp/pip-build-env-ajd08x5_/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 23, in <module>
    from packaging.tags import sys_tags
  File "/tmp/pip-build-env-ajd08x5_/overlay/lib/python3.10/site-packages/poetry/core/_vendor/packaging/tags.py", line 7, in <module>
    import distutils.util
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 92, in create_module
    return importlib.import_module('setuptools._distutils')
  File "/home/nsage/miniconda3/envs/pudl-dev/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'setuptools'

| 
failed

CondaEnvException: Pip failed
```

**Comment by zaneselvans** [comment]
Hey there, I haven't been able to reproduce this. I suspect that it's due to the release of `setuptools` 60.0, which apparently has some breaking changes for many packages.  If you edit `pyproject.toml` to constrain the version to < 60.0 and change the `devtools/environment.yml` to contain `setuptools<60.0.0` as well, does it work?

### `pyproject.toml`
```
[build-system]
requires = ["setuptools<60.0.0", "pip", "wheel", "setuptools_scm"]

[tool.setuptools_scm]
```

### `devtools/environment.yml`
add this line near the pip / python version requirements...
```
setuptools<60.0.0
```

**Comment by Wheelspawn** [comment]
That worked. Do you want me to make a pull request for this?

**Comment by zaneselvans** [comment]
Yes that would be great, thanks!
