### ISSUE TITLE
pre-commit.ci build step failing

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#2247]
This is blocking a bunch of dependabot PRs:
example https://results.pre-commit.ci/run/github/80646423/1675062145.4mZ3Sd25SX-v6Rk9zOamng

```
    stderr:
          error: subprocess-exited-with-error
      
          × Preparing metadata (pyproject.toml) did not run successfully.
          │ exit code: 1
          ╰─> [17 lines of output]
              Traceback (most recent call last):
                File "/pc/clone/FAyrB0nVQOi505WZ2l1j_w/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
                  main()
                File "/pc/clone/FAyrB0nVQOi505WZ2l1j_w/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
                  json_out['return_val'] = hook(**hook_input['kwargs'])
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/pc/clone/FAyrB0nVQOi505WZ2l1j_w/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
                  return hook(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/tmp/pip-build-env-55fevwc0/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
                  poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/tmp/pip-build-env-55fevwc0/overlay/lib/python3.11/site-packages/poetry/core/factory.py", line 57, in create_poetry
                  raise RuntimeError("The Poetry configuration is invalid:\n" + message)
              RuntimeError: The Poetry configuration is invalid:
                - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
              [end of output]
      
          note: This error originates from a subprocess, and is likely not a problem with pip.
        error: metadata-generation-failed
```

**Comment by jdangerx** [comment]
This appears to be due to [isort being at `5.11.4` instead of `5.12.0`](https://github.com/home-assistant/core/issues/86892). Updating that should fix things!
