### ISSUE TITLE
Running ETL Pipeline gets: No module named 'pudl'  

### ISSUE THREAD

**Issue by AppTrain** [catalyst-cooperative/pudl#2585]
### Describe the bug
After completing "Development Setup" instructions here:
https://catalystcoop-pudl.readthedocs.io/en/latest/dev/dev_setup.html

I'm trying "Running the ETL Pipeline"
https://catalystcoop-pudl.readthedocs.io/en/latest/dev/run_the_etl.html

In Database initialization when I run 
`alembic upgrade head`
I get:

ModuleNotFoundError: No module named 'pudl'

### Bug Severity

 - **Low:**

**Comment by zschira** [comment]
Hi, the first thing I'd check is that you've activated the `pudl-dev` environment before using the `alembic` command. You can do this by running `mamba activate pudl-dev`. If you're still having this problem after making sure the environment is active, I would try the following:

1. Deactivate environment - `mamba deactivate`
2. Remove environment - `mamba env remove --name pudl-dev`
3. Follow steps to [recreate the environment](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/dev_setup.html#create-the-pudl-dev-environment)

Then, try and activate the new environment, and run the alembic command again. If you're still having problems after this we can get some more info and try to figure it out, but hopefully getting the environment sorted out will solve your problem.

**Comment by AppTrain** [comment]
Thanks for the response,   I tried the above, recreated the environment and still get the error:

`(pudl-dev) apptrain@greenmachine:~/pudl$ alembic upgrade head
Traceback (most recent call last):
  File "/home/apptrain/.local/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/apptrain/.local/lib/python3.8/site-packages/alembic/config.py", line 591, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/apptrain/.local/lib/python3.8/site-packages/alembic/config.py", line 585, in main
    self.run_cmd(cfg, options)
  File "/home/apptrain/.local/lib/python3.8/site-packages/alembic/config.py", line 562, in run_cmd
    fn(
  File "/home/apptrain/.local/lib/python3.8/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/home/apptrain/.local/lib/python3.8/site-packages/alembic/script/base.py", line 576, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/apptrain/.local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/apptrain/.local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/apptrain/ppudl/migrations/env.py", line 7, in <module>
    from pudl.metadata.classes import Package
ModuleNotFoundError: No module named 'pudl'
(pudl-dev) apptrain@greenmachine:~/pudl$`
