### ISSUE TITLE
Data irregularities cause epacems_to_parquet to fail

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#451]
After (apparently) successfully running the new data package based ETL process on the full EPA CEMS dataset (all years, all states), I tried to run the `epacems_to_parquet` script, but it encountered errors, and ultimately failed.  Several errors were of the type:
```
sys:1: DtypeWarning: Columns (8,10,12,14) have mixed types. Specify dtype option on import or set low_memory=False.
```
But the thing that crashed it eventually was:
```
Traceback (most recent call last):
  File "/home/zane/miniconda3/envs/pudl-dev/bin/epacems_to_parquet", line 11, in <module>
    load_entry_point('catalystcoop.pudl', 'console_scripts', 'epacems_to_parquet')()
  File "/home/zane/pudl/src/pudl/convert/epacems_to_parquet.py", line 319, in main
    clobber=args.clobber)
  File "/home/zane/pudl/src/pudl/convert/epacems_to_parquet.py", line 205, in epacems_to_parquet
    df = year_from_operating_datetime(df).astype(IN_DTYPES)
  File "/home/zane/pudl/src/pudl/convert/epacems_to_parquet.py", line 123, in year_from_operating_datetime
    df['year'] = df.operating_datetime_utc.dt.year
  File "/home/zane/miniconda3/envs/pudl-dev/lib/python3.7/site-packages/pandas/core/generic.py", line 5175, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/zane/miniconda3/envs/pudl-dev/lib/python3.7/site-packages/pandas/core/accessor.py", line 175, in __get__
    accessor_obj = self._accessor(obj)
  File "/home/zane/miniconda3/envs/pudl-dev/lib/python3.7/site-packages/pandas/core/indexes/accessors.py", line 343, in __new__
    raise AttributeError("Can only use .dt accessor with datetimelike " "values")
AttributeError: Can only use .dt accessor with datetimelike values
```

**Comment by zaneselvans** [comment]
Hey @roll, after we got off the call this morning I realized that this seems to be something happening in the `datapackage.save()` step. When we're trying to put all the data in the EPA CEMS "resource group" into a single table in SQLite, for some reason it only seems to be loading the last year of several years which are part of the data package.  It may or may not be loading all of the different states (I've only done the ETL locally trying to load all the years of Colorado data, but instead I only get the 2018 Colorado data in the database). When I was trying to load the full 25 year / 50 state dataset, it finished very quickly, which suggests to me that it wasn't even trying to load all those other years and/or states, and instead just did a small subset of the work.

Is there any obvious reason you can think of why this might happen?  Here's what one of the resource descriptors looks like:
```
        {
            "profile": "tabular-data-resource",
            "name": "hourly_emissions_epacems_2002_co",
            "path": "data/hourly_emissions_epacems_2002_co.csv.gz",
            "title": "hourly_emissions_epacems",
            "encoding": "utf-8",
            "mediatype": "text/csv",
            "format": "csv",
            "dialect": {
                "delimiter": ",",
                "header": true,
                "quoteChar": "\"",
                "doubleQuote": true,
                "lineTerminator": "\r\n",
                "skipInitialSpace": true,
                "caseSensitiveHeader": false
            },
            "schema": {
                "fields": [
                    {
                        "name": "state",
                        "type": "string",
                        "constraints": {
                            "enum": [
                                "AL",
                                "AR",
                                "AZ",
                                "CA",
                                "CO",
                                "CT",
                                "DC",
                                "DE",
                                "FL",
                                "GA",
                                "IA",
                                "ID",
                                "IL",
                                "IN",
                                "KS",
                                "KY",
                                "LA",
                                "MA",
                                "MD",
                                "ME",
                                "MI",
                                "MN",
                                "MO",
                                "MS",
                                "MT",
                                "NC",
                                "ND",
                                "NE",
                                "NH",
                                "NJ",
                                "NM",
                                "NV",
                                "NY",
                                "OH",
                                "OK",
                                "OR",
                                "PA",
                                "RI",
                                "SC",
                                "SD",
                                "TN",
                                "TX",
                                "UT",
                                "VA",
                                "VT",
                                "WA",
                                "WI",
                                "WV",
                                "WY"
                            ]
                        },
                        "description": "State the plant is located in.",
                        "format": "default"
                    },
                    {
                        "name": "plant_id_eia",
                        "type": "integer",
                        "description": "The unique six-digit facility identification number, also called an ORISPL, assigned by the Energy Information Administration.",
                        "format": "default"
                    },
                    {
                        "name": "unitid",
                        "type": "string",
                        "description": "Facility-specific unit id (e.g. Unit 4)",
                        "format": "default"
                    },
                    {
                        "name": "operating_datetime_utc",
                        "type": "datetime",
                        "description": "Date and time measurement began (UTC).",
                        "format": "default"
                    },
                    {
                        "name": "operating_time_hours",
                        "type": "number",
                        "description": "Length of time interval measured.",
                        "format": "default"
                    },
                    {
                        "name": "gross_load_mw",
                        "type": "number",
                        "description": "Average power in megawatts produced during time interval measured.",
                        "format": "default"
                    },
                    {
                        "name": "steam_load_1000_lbs",
                        "type": "number",
                        "description": "Total steam pressure produced by a unit or source in any calendar year (or other specified time period) produced by combusting a given heat input of fuel.",
                        "format": "default"
                    },
                    {
                        "name": "so2_mass_lbs",
                        "type": "number",
                        "description": "Sulfur dioxide emissions in pounds.",
                        "format": "default"
                    },
                    {
                        "name": "so2_mass_measurement_code",
                        "type": "string",
                        "constraints": {
                            "enum": [
                                "LME",
                                "Measured",
                                "Measured and Substitute",
                                "Other",
                                "Substitute",
                                "Undetermined",
                                "Unknown Code",
                                ""
                            ]
                        },
                        "description": "Identifies whether the reported value of emissions was measured, calculated, or measured and substitute.",
                        "format": "default"
                    },
                    {
                        "name": "nox_rate_lbs_mmbtu",
                        "type": "number",
                        "description": "The average rate at which NOx was emitted during a given time period.",
                        "format": "default"
                    },
                    {
                        "name": "nox_rate_measurement_code",
                        "type": "string",
                        "constraints": {
                            "enum": [
                                "Calculated",
                                "LME",
                                "Measured",
                                "Measured and Substitute",
                                "Not Applicable",
                                "Other",
                                "Substitute",
                                "Undetermined",
                                "Unknown Code",
                                ""
                            ]
                        },
                        "description": "Identifies whether the reported value of emissions was measured, calculated, or measured and substitute.",
                        "format": "default"
                    },
                    {
                        "name": "nox_mass_lbs",
                        "type": "number",
                        "description": "NOx emissions in pounds.",
                        "format": "default"
                    },
                    {
                        "name": "nox_mass_measurement_code",
                        "type": "string",
                        "constraints": {
                            "enum": [
                                "Calculated",
                                "LME",
                                "Measured",
                                "Measured and Substitute",
                                "Not Applicable",
                                "Other",
                                "Substitute",
                                "Undetermined",
                                "Unknown Code",
                                ""
                            ]
                        },
                        "description": "Identifies whether the reported value of emissions was measured, calculated, or measured and substitute.",
                        "format": "default"
                    },
                    {
                        "name": "co2_mass_tons",
                        "type": "number",
                        "description": "Carbon dioxide emissions in short tons.",
                        "format": "default"
                    },
                    {
                        "name": "co2_mass_measurement_code",
                        "type": "string",
                        "constraints": {
                            "enum": [
                                "LME",
                                "Measured",
                                "Measured and Substitute",
                                "Other",
                                "Substitute",
                                "Undetermined",
                                "Unknown Code",
                                ""
                            ]
                        },
                        "description": "Identifies whether the reported value of emissions was measured, calculated, or measured and substitute.",
                        "format": "default"
                    },
                    {
                        "name": "heat_content_mmbtu",
                        "type": "number",
                        "description": "The energy contained in fuel burned, measured in million BTU.",
                        "format": "default"
                    },
                    {
                        "name": "facility_id",
                        "type": "integer",
                        "description": "Plant ID, assigned by the Energy Information Administration.",
                        "format": "default"
                    },
                    {
                        "name": "unit_id_epa",
                        "type": "integer",
                        "description": "Unit ID for each unit at a facility, assigned by the Energy Information Administration.",
                        "format": "default"
                    }
                ],
                "missingValues": [
                    ""
                ]
            },
            "licenses": [
                {
                    "name": "CC-BY-4.0",
                    "title": "Creative Commons Attribution 4.0",
                    "path": "https://creativecommons.org/licenses/by/4.0/"
                }
            ],
            "sources": [
                {
                    "title": "Environmental Protection Agency Continuous Emission Monitoring Systems",
                    "path": "ftp://newftp.epa.gov/dmdnload/emissions/hourly/monthly",
                    "source_code": "epacems",
                    "parameters_pudl": {
                        "epacems_years": [
                            1995,
                            1996,
                            1997,
                            1998,
                            1999,
                            2000,
                            2001,
                            2002,
                            2003,
                            2004,
                            2005,
                            2006,
                            2007,
                            2008,
                            2009,
                            2010,
                            2011,
                            2012,
                            2013,
                            2014,
                            2015,
                            2016,
                            2017,
                            2018
                        ],
                        "epacems_states": [
                            "CO"
                        ],
                        "partition": {
                            "hourly_emissions_epacems": [
                                "epacems_years",
                                "epacems_states"
                            ]
                        }
                    }
                }
            ],
            "bytes": 5551312,
            "hash": "sha256:5402de2870c8833947680b86e41f42797a58c9170b846ffc6d8aff69be4fbdd4",
            "created": "2019-10-12T05:04:39Z",
            "start_date": "1995-01-01",
            "end_date": "2018-21-31",
            "group": "hourly_emissions_epacems"
        },
```

**Comment by zaneselvans** [comment]
Hey @karldw have you run into any of these data issues with the EPA CEMS to parquet conversions? Seems like it doesn't affect *all* of the years/states, only some.  Do the errors above ring a bell?

**Comment by karldw** [comment]
Hmm, I didn't have this problem when the path was zipfile → parquet (that is, before #385), but I haven't tried the zipfile → datapackage → parquet path yet.

**Comment by karldw** [comment]
I tried the zipfile → datapackage → parquet path, using the development version 73c9dc2652d59e3741a9a0d64fbea1593bda0f99. I get the same error you do  for the state-years that have no data (e.g. Arkansas in 1995). 

I get a different error in other cases:
```bash
$ epacems_to_parquet --pkg_dir datapackage/pudl-epacems/epacems --year 2018 -c
2019-10-18 10:45:45 [    INFO] pudl:302 Checking for required EPA CEMS input files...
2019-10-18 10:45:48 [    INFO] pudl.convert.epacems_to_parquet:203 Converted 854160 records for 2018 and al.
2019-10-18 10:45:50 [    INFO] pudl.convert.epacems_to_parquet:203 Converted 359160 records for 2018 and ar.
2019-10-18 10:45:52 [    INFO] pudl.convert.epacems_to_parquet:203 Converted 779640 records for 2018 and az.
2019-10-18 10:45:59 [    INFO] pudl.convert.epacems_to_parquet:203 Converted 2165976 records for 2018 and ca.
2019-10-18 10:46:02 [    INFO] pudl.convert.epacems_to_parquet:203 Converted 621960 records for 2018 and co.
2019-10-18 10:46:04 [    INFO] pudl.convert.epacems_to_parquet:203 Converted 530328 records for 2018 and ct.
2019-10-18 10:46:05 [    INFO] pudl.convert.epacems_to_parquet:203 Converted 26280 records for 2018 and dc.
Traceback (most recent call last):
  File ".../bin/epacems_to_parquet", line 11, in <module>
    load_entry_point('catalystcoop.pudl', 'console_scripts', 'epacems_to_parquet')()
  File ".../src/pudl/convert/epacems_to_parquet.py", line 319, in main
    clobber=args.clobber)
  File ".../src/pudl/convert/epacems_to_parquet.py", line 208, in epacems_to_parquet
    df, preserve_index=False, schema=schema),
  File "pyarrow/table.pxi", line 1065, in pyarrow.lib.Table.from_pandas
  File "pyarrow/table.pxi", line 1093, in pyarrow.lib.Table.from_arrays
  File "pyarrow/table.pxi", line 452, in pyarrow.lib._sanitize_arrays
  File "pyarrow/array.pxi", line 233, in pyarrow.lib.asarray
  File "pyarrow/array.pxi", line 570, in pyarrow.lib.Array.cast
  File "pyarrow/error.pxi", line 86, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: No cast implemented from dictionary<values=double, indices=int8, ordered=0> to dictionary<values=string, indices=int8, ordered=0>

```

This one is also new to me, but looks like a pyarrow schema issue.

**Comment by zaneselvans** [comment]
By the "same error" do you mean both the Dtype warning and the datetime failure? Are those both related to year/state combos with no data?  (in which case I guess we just need to check whether the data exists for that year before attempting the conversion?).

What makes you think it's a schema issue, rather than a data issue -- i.e. are there some strings in there that need to be converted to floats, but they aren't convertible for some reason (leading zero, junk characters, etc.).

@cmgosnell just created dictionaries of data type by column for the EIA data, which explicitly cast every field to the required type after it's been cleaned up and before it's loaded into the CSVs.  Maybe doing something similar for the CEMS before it's written out would help? How can we get some specific examples of the records with apparent type mismatches that are breaking things?

**Comment by karldw** [comment]
I haven't seen the dtype warning. For the combination of states and years I've run, I hit one of the two errors first.

I think the schema issue is coming up for DC in 2018 because the `so2_mass_measurement_code` and `co2_mass_measurement_code` are all NaN. In the explicit schema `epacems_to_parquet` [provides](https://github.com/catalyst-cooperative/pudl/blob/b1fe1b3844c5c26f06047e7fdb1b6f1cdc052a23/src/pudl/convert/epacems_to_parquet.py#L99), these are (correctly) encoded as dictionaries of strings.

Debugging, omitting some output:
```
$ python3 -m pdb $(which epacems_to_parquet) --pkg_dir datapackage/pudl-epacems/epacems --year 2017 -c
(Pdb++) continue
...
Traceback (most recent call last):
pyarrow.lib.ArrowNotImplementedError: No cast implemented from dictionary<values=double, indices=int8, ordered=0> to dictionary<values=string, indices=int8, ordered=0>
Uncaught exception. Entering post mortem debugging
(Pdb++) up 6
(Pdb++) schema
year: int32 not null
state: dictionary<values=string, indices=int8, ordered=0>
plant_id_eia: int32 not null
unitid: string not null
operating_datetime_utc: timestamp[ms, tz=utc] not null
operating_time_hours: float
gross_load_mw: float not null
steam_load_1000_lbs: float
so2_mass_lbs: float
so2_mass_measurement_code: dictionary<values=string, indices=int8, ordered=0>
nox_rate_lbs_mmbtu: float
nox_rate_measurement_code: dictionary<values=string, indices=int8, ordered=0>
nox_mass_lbs: float
nox_mass_measurement_code: dictionary<values=string, indices=int8, ordered=0>
co2_mass_tons: float
co2_mass_measurement_code: dictionary<values=string, indices=int8, ordered=0>
heat_content_mmbtu: float not null
facility_id: int32
unit_id_epa: int32
(Pdb++) df.dtypes
state                                   category
plant_id_eia                               int64
unitid                                    object
operating_datetime_utc       datetime64[ns, UTC]
operating_time_hours                     float64
gross_load_mw                            float64
steam_load_1000_lbs                      float64
so2_mass_lbs                             float64
so2_mass_measurement_code               category
nox_rate_lbs_mmbtu                       float64
nox_rate_measurement_code               category
nox_mass_lbs                             float64
nox_mass_measurement_code               category
co2_mass_tons                            float64
co2_mass_measurement_code               category
heat_content_mmbtu                       float64
facility_id                              float32
unit_id_epa                              float32
year                                       int64

(Pdb++) import pyarrow
(Pdb++) pyarrow.lib.Table.from_pandas(df, schema=schema)
*** pyarrow.lib.ArrowNotImplementedError: No cast implemented from dictionary<values=double, indices=int8, ordered=0> to dictionary<values=string, indices=int8, ordered=0>
(Pdb++) dummy_cat = pd.CategoricalDtype(categories=['a'], ordered=False)
(Pdb++) df2 = df.astype({'so2_mass_measurement_code': dummy_cat, 'co2_mass_measurement_code': dummy_cat})
(Pdb++) pyarrow.lib.Table.from_pandas(df2, schema=schema) # now it works
```

It seems like pyarrow is unhappy converting a zero-category categorical column into a string categorical column. This is something pyarrow should handle, but since it doesn't (as of v0.15.0), we can get around the problem with more extensive `IN_DTYPES`.

Here's one (untested) option:
```python
IN_DTYPES = {
    "co2_mass_measurement_code": pd.CategoricalDtype(
        categories=[
            "LME",
            "Measured",
            "Measured and Substitute",
            "Other",
            "Substitute",
            "Undetermined",
            "Unknown Code",
            "",
        ],
        ordered=False,
    ),
    "nox_mass_measurement_code": pd.CategoricalDtype(
        categories=[
            "Calculated",
            "LME",
            "Measured",
            "Measured and Substitute",
            "Not Applicable",
            "Other",
            "Substitute",
            "Undetermined",
            "Unknown Code",
            "",
        ],
        ordered=False,
    ),
    "nox_rate_measurement_code": pd.CategoricalDtype(
        categories=[
            "Calculated",
            "LME",
            "Measured",
            "Measured and Substitute",
            "Not Applicable",
            "Other",
            "Substitute",
            "Undetermined",
            "Unknown Code",
            "",
        ],
        ordered=False,
    ),
    "so2_mass_measurement_code": pd.CategoricalDtype(
        categories=[
            "LME",
            "Measured",
            "Measured and Substitute",
            "Other",
            "Substitute",
            "Undetermined",
            "Unknown Code",
            "",
        ],
        ordered=False,
    ),
    # We know state is never missing, so we can use default category inference
    "state": "category",
    "unitid": "str",
    # Note: it'd be better to use pandas' nullable integers once this issue is
    # resolved: https://issues.apache.org/jira/browse/ARROW-5379
    # 'facility_id': "Int32",
    # 'unit_id_epa': "Int32",
    "facility_id": "float32",
    "unit_id_epa": "float32",
}

```

**Comment by karldw** [comment]
I wrote some [code](https://github.com/karldw/pudl/tree/bug-451) that should address this, but I'll test it later this week before creating a PR.

**Comment by zaneselvans** [comment]
Thank you for looking into all this @karldw!  I'm looking forward to finally playing around with the CEMS data soon and getting familiar with dask.

**Comment by roll** [comment]
@zaneselvans 
Is it something that's not yet confirmed to be a problem with Frictonless libs?

**Comment by zaneselvans** [comment]
@roll I don't think we know whether this would be an issue in the Frictonless libs -- right now the compressed CSV files are being read directly using `pands.read_csv` which isn't aware of the schema which is specified by `datapackage.json` When one reads a pandas DataFrame from a datapackge, does it automatically set the column data types based on the schema?  If so, and we can tell it to only read in a subset of the resources which are part of the big `epacems_hourly` table, then maybe reading the data into pandas using datapackage, before writing it out to parquet would get around this?

**Comment by roll** [comment]
@zaneselvans 
If using `tableschema-pandas-py` it should translate data types

**Comment by cmgosnell** [comment]
@roll thanks! we are not right now, but this is obviously what we should be doing. I'll spend some time converting this script to using it and see if that solves this problem

**Comment by cmgosnell** [comment]
@roll poking around at the `push_datapackage` going off of this [example](https://github.com/frictionlessdata/tableschema-pandas-py#example) like this:
```
datapkg_path = str(pathlib.Path(pudl_settings['datapackage_dir'], 'pudl_eia_only/eia-test/datapackage.json'))
storage = datapackage.push_datapackage(datapkg_path, 'pandas')
```
or even the example and I was getting this error:

```
~/miniconda3/envs/pudl-dev/lib/python3.7/site-packages/datapackage/pushpull.py in push_datapackage(descriptor, backend, **backend_options)
     49 
     50     # Get storage
---> 51     plugin = import_module('jsontableschema.plugins.%s' % backend)
     52     storage = plugin.Storage(**backend_options)
     53 

~/miniconda3/envs/pudl-dev/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 
ModuleNotFoundError: No module named 'jsontableschema'
```

I have tableschema-pandas version 1.0.0 installed.

```
(pudl-dev) %0 ~/code/pudl/devtools% conda list tableschema-pandas                                                             christinagosnell@New-Shiny-Thing

# packages in environment at /Users/christinagosnell/miniconda3/envs/pudl-dev:
#
# Name                    Version                   Build  Channel
tableschema-pandas        1.0.0                    pypi_0    pypi
```

So I tried `pip install jsontableschema`, which then got me to this error with both the [example](https://github.com/frictionlessdata/tableschema-pandas-py#example) package and the pudl package:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-741ad89e97a3> in <module>
      1 data_url = 'http://data.okfn.org/data/core/country-list/datapackage.json'
----> 2 storage = datapackage.push_datapackage(data_url, 'pandas')

~/miniconda3/envs/pudl-dev/lib/python3.7/site-packages/datapackage/pushpull.py in push_datapackage(descriptor, backend, **backend_options)
     46 
     47     # Init model
---> 48     model = Package(descriptor)
     49 
     50     # Get storage

~/miniconda3/envs/pudl-dev/lib/python3.7/site-packages/datapackage/package.py in __init__(self, descriptor, base_path, strict, storage, schema, default_base_path, **options)
    104 
    105         # Build package
--> 106         self.__build()
    107 
    108     def __del__(self):

~/miniconda3/envs/pudl-dev/lib/python3.7/site-packages/datapackage/package.py in __build(self)
    316 
    317         # Instantiate profile
--> 318         self.__profile = Profile(self.__current_descriptor.get('profile'))
    319 
    320         # Validate descriptor

~/miniconda3/envs/pudl-dev/lib/python3.7/site-packages/datapackage/profile.py in __init__(self, profile)
     27         self._registry = self._load_registry()
     28         self._schema = self._load_schema(profile, self._registry)
---> 29         self._validator = self._load_validator(self._schema, self._registry)
     30         self._check_schema()
     31 

~/miniconda3/envs/pudl-dev/lib/python3.7/site-packages/datapackage/profile.py in _load_validator(self, schema, registry)
    104 
    105     def _load_validator(self, schema, registry):
--> 106         validator_class = jsonschema.validators.validator_for(schema)
    107         return validator_class(schema)
    108 

AttributeError: module 'jsonschema' has no attribute 'validators'
```

**Comment by roll** [comment]
@cmgosnell 
Sorry for the confusion but the example is out-dated. It works the same way as all other drivers:
https://github.com/frictionlessdata/testsuite-extended/blob/master/tests/test_datapackage.py#L59

**Comment by cmgosnell** [comment]
Hey @roll. thanks for the pointer! this got me through the `Package()` definition step.. and sorry to keep bugging you with errors, but now on `package.save(storage=storage)` I'm getting this error: 

```
StorageError: Multi-column primary keys are not supported
```

we are definitely using multi-column PKs in many of our tables. Do you know if that is this an expected error for this type of application or am I doing something strange?

The full error is here: 
```
---------------------------------------------------------------------------
StorageError                              Traceback (most recent call last)
<ipython-input-14-ba9d352b9895> in <module>
      6                                'pudl_cems',
      7                                'pudl-all', 'datapackage.json'))))
----> 8 package.save(storage=storage)
      9 
     10 # Load

~/miniconda3/envs/pudl-dev/lib/python3.7/site-packages/datapackage/package.py in save(self, target, storage, merge_groups, **options)
    269             for bucket in storage.buckets:
    270                 source = sources[buckets.index(bucket)]
--> 271                 storage.write(bucket, source())
    272 
    273         # Save descriptor to json

~/miniconda3/envs/pudl-dev/lib/python3.7/site-packages/tableschema_pandas/storage.py in write(self, bucket, rows)
    147         # Prepare
    148         descriptor = self.describe(bucket)
--> 149         new_data_frame = self.__mapper.convert_descriptor_and_rows(descriptor, rows)
    150 
    151         # Just set new DataFrame if current is empty

~/miniconda3/envs/pudl-dev/lib/python3.7/site-packages/tableschema_pandas/mapper.py in convert_descriptor_and_rows(self, descriptor, rows)
     38         elif len(schema.primary_key) > 1:
     39             message = 'Multi-column primary keys are not supported'
---> 40             raise tableschema.exceptions.StorageError(message)
     41 
     42         # Get data/index

StorageError: Multi-column primary keys are not supported
```

**Comment by roll** [comment]
@cmgosnell 
Please try `tableschema-pandas@1.1`. I have added support for composite primary keys
