### ISSUE TITLE
Obscure prefect exception can happen during development

### ISSUE THREAD

**Issue by rousik** [catalyst-cooperative/pudl#908]
Sometimes when I'm coding and testing my changes by running test etl, the prefect library throws this obscure exception:

```
[2021-02-05 18:18:21-0700] ERROR - prefect.FlowRunner | Unexpected error: TypeError("object of type 'KeyError' has no len()")
Traceback (most recent call last):
  File "/home/jaro/data/anaconda3/envs/p2/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/home/jaro/data/anaconda3/envs/p2/lib/python3.8/site-packages/prefect/engine/flow_runner.py", line 494, in get_flow_run_state
    children = executors.flatten_mapped_children(
  File "/home/jaro/data/anaconda3/envs/p2/lib/python3.8/site-packages/prefect/utilities/executors.py", line 559, in flatten_mapped_children
    [executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
  File "/home/jaro/data/anaconda3/envs/p2/lib/python3.8/site-packages/prefect/utilities/executors.py", line 559, in <listcomp>
    [executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
  File "/home/jaro/data/anaconda3/envs/p2/lib/python3.8/site-packages/prefect/executors/local.py", line 28, in submit
    return fn(*args, **kwargs)
  File "/home/jaro/data/anaconda3/envs/p2/lib/python3.8/site-packages/prefect/utilities/executors.py", line 559, in <lambda>
    [executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
TypeError: object of type 'KeyError' has no len()
```

Usually, there are also associated task failures (perhaps this happens when mapped task gets strange input) but this feels like a prefect bug because it is making incorrect type assumptions.

In this case, `KeyError` seems to be stored in `c._result.value` while the code assumes list here.

This exception seems to propagate and crash `flow.run()`

**Comment by rousik** [comment]
It seems that storing exceptions in the results is a feature described here: https://docs.prefect.io/core/advanced_tutorials/local-debugging.html#re-raising-execeptions-post-hoc which makes it even more surprising that the code did not handle it well.

**Comment by rousik** [comment]
Poked at this some more and filed https://github.com/PrefectHQ/prefect/issues/4084 against prefect codebase along with a simple example of a failing flow.

**Comment by zaneselvans** [comment]
No longer relevant due to the Dagster refactor. See e.g. #1960 #2104
